@startuml nested-sets

' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity Message {
  * id: varchar
  --
  * nsleft: varchar
  * nsright: varchar
  * text: varchar
}

@enduml
