@startuml path-enum

' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity Message {
  * id: varchar
  --
  * path: varchar
  * text: varchar
}

@enduml
