@startuml database-design-6

' hide the spot
hide circle
' avoid problems with angled crows feet
' skinparam linetype ortho

entity 投稿 {
  *投稿ID (int)
  --
  *ワークスペース_チャンネル_ユーザー_ID <<FK>>
  *メッセージ (varchar)
  *投稿日時 (datetime)
}

entity 投稿ツリーパス {
  *投稿ID AS 先祖 <<FK>>
  *投稿ID AS 子孫 <<FK>>
  --
  *深さ (int)
}

entity ユーザー {
  *ユーザーID (int)
  --
  *名前 (varchar)
  *表示名 (varchar)
  *メールアドレス (varchar)
}

entity チャンネル {
  *チャンネルID (int)
  --
  *名前 (varchar)
}

entity ワークスペース {
  *ワークスペースID
  --
  *名前
}

entity ワークスペース_チャンネル_ユーザー {
  *ワークスペース_チャンネル_ユーザー_ID
  --
  *ワークスペースID <<FK>>
  *チャンネルID <<FK>>
  *ユーザーID <<FK>>
}

投稿 ||--|{ 投稿ツリーパス
投稿 ||--|{ 投稿ツリーパス
投稿 ||--|{ ワークスペース_チャンネル_ユーザー
ワークスペース }|--|| ワークスペース_チャンネル_ユーザー
チャンネル }|-u-|| ワークスペース_チャンネル_ユーザー
ユーザー }|--|| ワークスペース_チャンネル_ユーザー

@enduml
