@startuml domain-model

' hide the spot
hide circle

rectangle 参加者 {
  entity 参加者 {
    参加者ID
    --
    名前
    メールアドレス
    在籍ステータス
    List<課題>
  }
}
note right of 参加者
- メールアドレスは重複不可。
- 在籍ステータスは「在籍中」「休会中」「退会済」の3つ。
- ステータスが「在籍中」以外の場合、
  どのチームにもペアにも所属してはいけない。
- 「休会中」の参加者が「在籍中」に切り替わった場合、
  所属チームは、最も参加人数が少ないチームから自動的に選ばれる。
  所属ペアは、最も参加人数が少ないペアから自動的に選ばれる。
end note


rectangle チーム {
  entity チーム {
    チームID
    --
    名前
    List<参加者>
  }
}
note top of チーム
- 名前は3桁以下の数値かつ重複不可。
- 最低でも参加者が3名いなければならない。

- チームに参加者が増える場合、特段のルールなし。
- チームに参加者が減る場合、
  2名以下のチームは存続できないため、参加者は自動的に他のチームに合流する。
  合流先は、最も参加人数が少ないチームから自動的に選ばれる。
  参加人数が同じチームが存在する場合はランダムに選択する。
end note


rectangle ペア {
  entity ペア {
    ペアID
    --
    名前
    List<参加者>
  }
}
note bottom of ペア
- 名前は1文字の英字。
- 参加者は2名〜3名まで。

- ペアに参加者が増える場合、
  4名のペアは存在できないため、自動的に2つのペアに分解する。
  参加者のペアの分解は、自動的に選ばれる。
- ペアから参加者が減る場合、
  1名のペアは存在できないため、自動的に他のペアに合流する。
  合流先は、最も参加人数の少ないペアから自動的に選ばれる。
  参加人数が同じペアが存在する場合はランダムに選択する。
end note

rectangle 課題 {
  entity 課題 {
    課題ID
    --
    タイトル
    学ばないと何が起きるのか
    課題説明
    完了条件
    進捗ステータス
  }
}
note bottom of 課題
- 進捗ステータスは「未着手、レビュー待ち、完了」の3つ。
- 進捗ステータスはいつでも変更可能。
- ただし一度「完了」にした進捗ステータスを
  「レビュー待ち」「未着手」に戻すことはできない。
- 進捗ステータスを変更できるのは、課題の所有者だけ。
end note


参加者 "3.." <-- "1" チーム
参加者 "2..3" <-- "1" ペア
参加者 "1" --> "1.." 課題

@enduml
