@startuml usecase

left to right direction
actor 参加者
package プラハチャレンジ {
  usecase 在籍ステータスを変更する as uc1
  usecase 課題の進捗ステータスを変更する as uc2
  ' usecase 他のチームに合流する
  ' usecase 他のペアに合流する
}
参加者 --> uc1
参加者 --> uc2

@enduml
